packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  workerd: true
  "@clerk/shared": true
  sharp: true
  bufferutil: true
  utf-8-validate: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@tanstack/*"
  - cn
  - wrangler
  - workerd
  - miniflare
  - "@cloudflare/workerd-*"
  - "@cloudflare/workers-types"

nodeLinker: hoisted
shamefullyHoist: true
linkWorkspacePackages: true
